### ISSUE TITLE
Extra blank line exists in the slides

### ISSUE THREAD

**Issue by meifish** [ithomaslin/autocuerr#1] opened 2017-06-08 13:14 UTC
When rendering slides from docs by using autocuerr, there occasionally would have extra blank lines appear below the text. Please see the following screenshot as reference.

![image](https://user-images.githubusercontent.com/10296596/26929973-522bd192-4c8e-11e7-9ce4-5127ac6111fd.png)

[Possible bug resolution]
This bug could result from the line-break symbols processing. There are two line-break symbols, /r and /r/n, for linux/MAC and windows system respectively. If the line processing only deals with /r, then when encountering /r/n line breaker, the dangling /n would form a new line with empty value.

Thanks for the update!

Best regards,

**Comment by ithomaslin** [comment] 2017-06-08 13:20
The issue is fixed in [the new commit](https://github.com/ithomaslin/autocuerr/commit/f3cecfe2b02d434a42b04ca8fef24c91309c50f9).

Marking it as resolved.

**Closed by ithomaslin** 2017-06-08 13:20 UTC
